### PR TITLE
packaging: spec file to build bluebanquise RPMS

### PR DESCRIPTION
**Pull request by actatux**
Defaults to current release 1.2.0.

This commit also removes execution bit on 2 ipxe files to avoid a build
failure with brp-mangle-shebangs.

### CODE REVIEW

**Comment by actatux** [comment]
**PR for review only.** Don't merge yet, I still need to add the `ansible.cfg` and the content of the `resources` directory to the RPMS.

**Comment by oxedions** [comment]
Please tell me when I can merge this one.

I will work tomorrow quickly on fixing the python code that break checks.

**Comment by actatux** [comment]
I still need to implement the %config and %config(noreplace) for the addons RPMS.

See https://www.cl.cam.ac.uk/~jw35/docs/rpm_config.html for a clear explanation of the RPM behavior with these directives.

> The files in roles/\<role>/vars/ are %config files.
> The files in roles/\<role>/{files,templates}/ are %config(noreplace)
> files.

Does this make sense to all?

**Comment by actatux** [comment]
PR is ready for merge.

**Comment by oxedions** [comment]
Dear @actatux 

This is perfect for me. If validated by others, I merge it.

Again sorry for the autocheck disturbance, I am on it.

Ben

**Pull request merged**
